// components/CommandPalette.vue
<template>
  <v-dialog
    v-model="isOpen"
    max-width="600"
  >
    <v-card class="rounded-2xl overflow-hidden">
      <div class="flex flex-col bg-surface text-foreground shadow-2xl">
        <!-- Search input -->
        <div class="flex items-center px-4 py-3.5 border-b border-border/60">
          <i class="mdi mdi-magnify text-muted mr-2"></i>
          <input
            ref="searchInput"
            v-model="query"
            type="text"
            placeholder="Search tickets, customers, inventory…"
            class="command-input flex-grow bg-transparent border-none outline-none text-sm font-medium text-foreground w-full placeholder-muted-foreground"
            @keydown.esc="isOpen = false"
            @keydown.down.prevent="moveSelection(1)"
            @keydown.up.prevent="moveSelection(-1)"
            @keydown.enter.prevent="executeSelected"
          />
          <span class="text-[10px] font-bold px-1.5 py-0.5 rounded border border-border/80 text-muted-foreground bg-muted shrink-0 select-none">ESC</span>
        </div>

        <!-- Results -->
        <div class="command-results max-h-[380px] overflow-y-auto">
          <!-- Empty state -->
          <div v-if="!query" class="p-8 text-center flex flex-col items-center gap-3">
            <i class="mdi mdi-text-search text-4xl text-muted"></i>
            <p class="text-xs text-muted-foreground font-medium">Type to search across everything</p>
            <div class="flex justify-center gap-2 mt-1">
              <span class="text-[9px] font-bold px-2.5 py-0.5 rounded-full bg-amber-500/10 text-amber-600">Tickets</span>
              <span class="text-[9px] font-bold px-2.5 py-0.5 rounded-full bg-blue-500/10 text-blue-600">Customers</span>
              <span class="text-[9px] font-bold px-2.5 py-0.5 rounded-full bg-purple-500/10 text-purple-600">Inventory</span>
            </div>
          </div>

          <!-- No results -->
          <div v-else-if="allResults.length === 0" class="p-8 text-center flex flex-col items-center gap-2">
            <i class="mdi mdi-emoticon-sad-outline text-4xl text-muted"></i>
            <p class="text-xs text-muted-foreground font-medium">No results for "{{ query }}"</p>
          </div>

          <!-- Grouped results -->
          <template v-else>
            <!-- Tickets -->
            <div v-if="ticketResults.length" class="py-2">
              <p class="text-[10px] font-black text-muted-foreground/80 uppercase tracking-wider px-4 py-1.5 flex items-center gap-1.5">
                <i class="mdi mdi-ticket-outline text-xs"></i> Tickets ({{ ticketResults.length }})
              </p>
              <div class="flex flex-col px-2 gap-0.5">
                <div
                  v-for="(item, idx) in ticketResults"
                  :key="'t-' + item.id"
                  class="flex items-center justify-between px-3 py-2 rounded-xl cursor-pointer transition-colors"
                  :class="[
                    selectedIndex === getGlobalIndex('ticket', idx)
                      ? 'bg-primary/10 text-primary'
                      : 'hover:bg-muted/50'
                  ]"
                  @click="goToTicket(item)"
                  @mouseenter="selectedIndex = getGlobalIndex('ticket', idx)"
                >
                  <div class="flex items-center gap-2.5 min-w-0">
                    <span 
                      class="text-[9px] font-bold px-1.5 py-0.5 rounded-md shrink-0"
                      :class="getStatusBadgeClass(item.status)"
                    >
                      #{{ item.id }}
                    </span>
                    <div class="min-w-0 leading-tight">
                      <p class="text-xs font-semibold truncate text-foreground">{{ item.device }} {{ item.deviceModel || '' }}</p>
                      <p class="text-[10px] text-muted-foreground truncate mt-0.5">{{ getCustomerName(item.customerId) }} · {{ item.status }}</p>
                    </div>
                  </div>
                  <span class="text-xs font-black text-emerald-600 dark:text-emerald-400 shrink-0">{{ formatCurrency(item.price) }}</span>
                </div>
              </div>
            </div>

            <!-- Customers -->
            <div v-if="customerResults.length" class="py-2">
              <p class="text-[10px] font-black text-muted-foreground/80 uppercase tracking-wider px-4 py-1.5 flex items-center gap-1.5">
                <i class="mdi mdi-account-group text-xs"></i> Customers ({{ customerResults.length }})
              </p>
              <div class="flex flex-col px-2 gap-0.5">
                <div
                  v-for="(item, idx) in customerResults"
                  :key="'c-' + item.id"
                  class="flex items-center gap-3 px-3 py-2 rounded-xl cursor-pointer transition-colors"
                  :class="[
                    selectedIndex === getGlobalIndex('customer', idx)
                      ? 'bg-primary/10 text-primary'
                      : 'hover:bg-muted/50'
                  ]"
                  @click="goToCustomer(item)"
                  @mouseenter="selectedIndex = getGlobalIndex('customer', idx)"
                >
                  <div 
                    class="w-7 h-7 rounded-full flex items-center justify-center text-[10px] font-black text-white shrink-0 shadow-sm"
                    :style="{ backgroundColor: avatarColor(item.name) }"
                  >
                    {{ initials(item.name) }}
                  </div>
                  <div class="min-w-0 leading-tight">
                    <p class="text-xs font-semibold truncate text-foreground">{{ item.name }}</p>
                    <p class="text-[10px] text-muted-foreground truncate mt-0.5">{{ item.phone || item.email || 'No contact' }}</p>
                  </div>
                </div>
              </div>
            </div>

            <!-- Inventory -->
            <div v-if="inventoryResults.length" class="py-2">
              <p class="text-[10px] font-black text-muted-foreground/80 uppercase tracking-wider px-4 py-1.5 flex items-center gap-1.5">
                <i class="mdi mdi-package-variant-closed text-xs"></i> Inventory ({{ inventoryResults.length }})
              </p>
              <div class="flex flex-col px-2 gap-0.5">
                <div
                  v-for="(item, idx) in inventoryResults"
                  :key="'i-' + item.id"
                  class="flex items-center justify-between px-3 py-2 rounded-xl cursor-pointer transition-colors"
                  :class="[
                    selectedIndex === getGlobalIndex('inventory', idx)
                      ? 'bg-primary/10 text-primary'
                      : 'hover:bg-muted/50'
                  ]"
                  @click="goToInventory()"
                  @mouseenter="selectedIndex = getGlobalIndex('inventory', idx)"
                >
                  <div class="flex items-center gap-3 min-w-0">
                    <div class="w-7 h-7 rounded-lg bg-purple-500/10 text-purple-500 flex items-center justify-center shrink-0">
                      <i class="mdi mdi-package-variant text-sm"></i>
                    </div>
                    <div class="min-w-0 leading-tight">
                      <p class="text-xs font-semibold truncate text-foreground">{{ item.name }}</p>
                      <p class="text-[10px] text-muted-foreground truncate mt-0.5">{{ item.sku || 'No SKU' }} · {{ item.stock }} in stock</p>
                    </div>
                  </div>
                  <span 
                    class="text-xs font-bold shrink-0"
                    :class="item.stock <= (item.low || 5) ? 'text-red-500' : 'text-emerald-600 dark:text-emerald-400'"
                  >
                    {{ formatCurrency(item.price) }}
                  </span>
                </div>
              </div>
            </div>
          </template>
        </div>

        <!-- Footer -->
        <div class="flex items-center justify-between px-4 py-2.5 border-t border-border/60 text-[10px] text-muted-foreground bg-muted/30 shrink-0">
          <div class="flex items-center gap-3 font-semibold">
            <span><kbd class="px-1 py-0.5 bg-muted border rounded">↑↓</kbd> Navigate</span>
            <span><kbd class="px-1 py-0.5 bg-muted border rounded">↵</kbd> Open</span>
            <span><kbd class="px-1 py-0.5 bg-muted border rounded">esc</kbd> Close</span>
          </div>
          <span class="font-bold opacity-75">⌘K</span>
        </div>
      </div>
    </v-card>
  </v-dialog>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue'
import { storeToRefs } from 'pinia'
import { useAppStore } from '~/stores/app'

const props = defineProps<{ modelValue: boolean }>()
const emit = defineEmits(['update:modelValue'])

const appStore = useAppStore()
const { tickets, customers, inventory, settings } = storeToRefs(appStore)

const isOpen = computed({
  get: () => props.modelValue,
  set: (val) => emit('update:modelValue', val),
})

const query = ref('')
const selectedIndex = ref(0)
const searchInput = ref<HTMLInputElement | null>(null)

// Reset on open
watch(isOpen, (val) => {
  if (val) {
    query.value = ''
    selectedIndex.value = 0
    nextTick(() => searchInput.value?.focus())
  }
})

// Search logic
const MAX = 5
const ticketResults = computed(() => {
  if (!query.value) return []
  const q = query.value.toLowerCase()
  return (tickets.value || []).filter(t =>
    String(t.id).includes(q) ||
    t.device?.toLowerCase().includes(q) ||
    (t.deviceModel || '').toLowerCase().includes(q) ||
    t.issue?.toLowerCase().includes(q) ||
    getCustomerName(t.customerId).toLowerCase().includes(q)
  ).slice(0, MAX)
})

const customerResults = computed(() => {
  if (!query.value) return []
  const q = query.value.toLowerCase()
  return (customers.value || []).filter(c =>
    c.name?.toLowerCase().includes(q) ||
    (c.phone || '').includes(q) ||
    (c.email || '').toLowerCase().includes(q)
  ).slice(0, MAX)
})

const inventoryResults = computed(() => {
  if (!query.value) return []
  const q = query.value.toLowerCase()
  return (inventory.value || []).filter((i: any) =>
    i.name?.toLowerCase().includes(q) ||
    (i.sku || '').toLowerCase().includes(q) ||
    (i.category || '').toLowerCase().includes(q)
  ).slice(0, MAX)
})

const allResults = computed(() => [
  ...ticketResults.value.map(t => ({ type: 'ticket', ...t })),
  ...customerResults.value.map(c => ({ type: 'customer', ...c })),
  ...inventoryResults.value.map(i => ({ type: 'inventory', ...i })),
])

function getGlobalIndex(type: string, localIdx: number) {
  if (type === 'ticket') return localIdx
  if (type === 'customer') return ticketResults.value.length + localIdx
  return ticketResults.value.length + customerResults.value.length + localIdx
}

function moveSelection(dir: number) {
  const total = allResults.value.length
  if (total === 0) return
  selectedIndex.value = (selectedIndex.value + dir + total) % total
}

function executeSelected() {
  const item = allResults.value[selectedIndex.value]
  if (!item) return
  if (item.type === 'ticket') goToTicket(item)
  else if (item.type === 'customer') goToCustomer(item)
  else goToInventory()
}

function goToTicket(t: any) {
  isOpen.value = false
  navigateTo(`/bookings?ticket=${t.id}`)
}

function goToCustomer(c: any) {
  isOpen.value = false
  navigateTo(`/customers?highlight=${c.id}`)
}

function goToInventory() {
  isOpen.value = false
  navigateTo('/inventory')
}

// Helpers
const formatCurrency = (n: number) => `${settings.value?.currency || '$'}${(n || 0).toFixed(2)}`
const getCustomerName = (id: number) => (customers.value || []).find((c: any) => c.id === id)?.name || 'Unknown'

const getStatusBadgeClass = (s: string) => {
  const mapping: Record<string, string> = {
    Open: 'bg-blue-500/10 text-blue-500',
    'In Progress': 'bg-amber-500/10 text-amber-500',
    'Waiting for Parts': 'bg-red-500/10 text-red-500',
    Completed: 'bg-emerald-500/10 text-emerald-500',
    Delivered: 'bg-gray-500/10 text-gray-500'
  }
  return mapping[s] || 'bg-gray-500/10 text-gray-500'
}

const AVATAR_COLORS = ['#6366f1','#3b82f6','#10b981','#f59e0b','#ec4899','#8b5cf6','#06b6d4','#ef4444']
const avatarColor = (name: string) => AVATAR_COLORS[(name?.charCodeAt(0) || 0) % AVATAR_COLORS.length]
const initials = (name: string) => {
  if (!name) return '?'
  const parts = name.trim().split(' ')
  return parts.length >= 2 ? (parts[0][0] + parts[parts.length - 1][0]).toUpperCase() : name.slice(0, 2).toUpperCase()
}
</script>

// src/components/CommandPalette.tsx
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Modal } from "@heroui/react";
import {
  CalendarDays,
  LayoutDashboard,
  Mail,
  Package,
  Repeat,
  Search,
  SlidersHorizontal,
  Ticket as TicketIcon,
  Users,
} from "lucide-react";

import type { Customer, InventoryItem, Ticket } from "@/types/domain";
import { sbFetchCustomers, sbFetchInventory, sbFetchTickets } from "@/lib/supabase";

const NAV_LINKS = [
  { label: "Dashboard", path: "/dashboard", icon: LayoutDashboard },
  { label: "Tickets", path: "/tickets", icon: TicketIcon },
  { label: "Customers", path: "/customers", icon: Users },
  { label: "Inventory", path: "/inventory", icon: Package },
  { label: "Trade-In", path: "/trade-in", icon: Repeat },
  { label: "Calendar", path: "/calendar", icon: CalendarDays },
  { label: "Messages", path: "/messages", icon: Mail },
  { label: "Settings", path: "/settings", icon: SlidersHorizontal },
];

interface Result {
  key: string;
  label: string;
  sublabel: string;
  icon: typeof TicketIcon;
  onSelect: () => void;
}

export default function CommandPalette() {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [inventory, setInventory] = useState<InventoryItem[]>([]);
  const [loadedOnce, setLoadedOnce] = useState(false);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setOpen((o) => !o);
      }
      if (e.key === "Escape") setOpen(false);
    };

    const openHandler = () => setOpen(true);

    window.addEventListener("keydown", handler);
    window.addEventListener("novaops:open-command-palette", openHandler);

    return () => {
      window.removeEventListener("keydown", handler);
      window.removeEventListener("novaops:open-command-palette", openHandler);
    };
  }, []);

  useEffect(() => {
    if (!open || loadedOnce) return;
    setLoadedOnce(true);
    sbFetchTickets().then(({ data }) => data && setTickets(data));
    sbFetchCustomers().then(({ data }) => data && setCustomers(data));
    sbFetchInventory().then(({ data }) => data && setInventory(data));
  }, [open, loadedOnce]);

  const go = (path: string) => {
    navigate(path);
    setOpen(false);
    setQuery("");
  };

  const results = useMemo<Result[]>(() => {
    const q = query.trim().toLowerCase();

    if (!q) return [];

    const ticketResults: Result[] = tickets
      .filter((t) => `${t.device} ${t.device_model} ${t.issue} ${t.id}`.toLowerCase().includes(q))
      .slice(0, 6)
      .map((t) => ({
        key: `t-${t.id}`,
        label: `${t.device} ${t.device_model}`.trim(),
        sublabel: `Ticket #${t.id} · ${t.status}`,
        icon: TicketIcon,
        onSelect: () => go(`/tickets?open=${t.id}`),
      }));

    const customerResults: Result[] = customers
      .filter((c) => `${c.name} ${c.phone} ${c.email}`.toLowerCase().includes(q))
      .slice(0, 6)
      .map((c) => ({
        key: `c-${c.id}`,
        label: c.name,
        sublabel: c.phone || c.email || "Customer",
        icon: Users,
        onSelect: () => go(`/customers?open=${c.id}`),
      }));

    const inventoryResults: Result[] = inventory
      .filter((i) => `${i.name} ${i.sku}`.toLowerCase().includes(q))
      .slice(0, 6)
      .map((i) => ({
        key: `i-${i.id}`,
        label: i.name,
        sublabel: i.sku || "Inventory item",
        icon: Package,
        onSelect: () => go(`/inventory?open=${i.id}`),
      }));

    const navResults: Result[] = NAV_LINKS.filter((n) => n.label.toLowerCase().includes(q)).map((n) => ({
      key: `nav-${n.path}`,
      label: n.label,
      sublabel: "Go to page",
      icon: n.icon,
      onSelect: () => go(n.path),
    }));

    return [...ticketResults, ...customerResults, ...inventoryResults, ...navResults];
  }, [query, tickets, customers, inventory]);

  return (
    <Modal>
      <Modal.Backdrop isOpen={open} onOpenChange={setOpen}>
        <Modal.Container size="md">
          <Modal.Dialog>
            <div className="flex items-center gap-2 border-b border-border px-4 py-3">
              <Search className="size-4 text-muted" />
              <input
                autoFocus
                className="w-full flex-1 bg-transparent text-sm outline-none placeholder:text-muted"
                placeholder="Search tickets, customers, inventory, or pages…"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
              />
              <span className="shrink-0 rounded border border-border px-1.5 py-0.5 text-micro font-bold text-muted">ESC</span>
            </div>
            <div className="max-h-[380px] overflow-y-auto p-2">
              {!query ? (
                <div className="flex flex-col items-center gap-2 p-8 text-center text-sm text-muted">
                  <Search className="size-8" />
                  <p className="m-0">Type to search across everything, or press a page name.</p>
                </div>
              ) : results.length === 0 ? (
                <p className="m-0 p-8 text-center text-sm text-muted">No results for "{query}"</p>
              ) : (
                results.map((r) => (
                  <button
                    key={r.key}
                    className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left transition-colors hover:bg-surface-secondary"
                    type="button"
                    onClick={r.onSelect}
                  >
                    <r.icon className="size-4 shrink-0 text-accent" />
                    <div className="min-w-0 flex-1">
                      <strong className="block truncate text-sm text-foreground">{r.label}</strong>
                      <span className="block truncate text-xs text-muted">{r.sublabel}</span>
                    </div>
                  </button>
                ))
              )}
            </div>
          </Modal.Dialog>
        </Modal.Container>
      </Modal.Backdrop>
    </Modal>
  );
}
