// components/SignaturePad.vue
<template>
  <div class="flex flex-col gap-2">
    <label class="text-[10px] font-bold text-muted-foreground uppercase tracking-wide">{{ label }}</label>
    <div class="border border-border rounded-xl overflow-hidden bg-surface">
      <canvas
        ref="canvasRef"
        :width="width"
        :height="height"
        class="touch-none"
        style="cursor:crosshair"
        @mousedown="startDrawing"
        @mousemove="draw"
        @mouseup="stopDrawing"
        @mouseleave="stopDrawing"
        @touchstart.prevent="startDrawing"
        @touchmove.prevent="draw"
        @touchend.prevent="stopDrawing"
      />
    </div>
    <div class="flex gap-2 mt-1">
      <Button 
        label="Clear" 
        icon="mdi mdi-close" 
        variant="outlined" 
        severity="secondary" 
        class="rounded-full text-xs font-bold text-none" 
        @click="clear" 
      />
      <Button 
        label="Save Signature" 
        icon="mdi mdi-content-save" 
        variant="outlined" 
        severity="primary" 
        class="rounded-full text-xs font-bold text-none" 
        @click="save" 
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

const props = defineProps<{
  label?: string
  width?: number
  height?: number
  modelValue?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const canvasRef = ref<HTMLCanvasElement | null>(null)
const isDrawing = ref(false)
const ctx = ref<CanvasRenderingContext2D | null>(null)

onMounted(() => {
  if (canvasRef.value) {
    ctx.value = canvasRef.value.getContext('2d')
    if (ctx.value) {
      ctx.value.strokeStyle = '#000'
      ctx.value.lineWidth = 2
      ctx.value.lineCap = 'round'
    }

    // Load existing signature
    if (props.modelValue) {
      const img = new Image()
      img.onload = () => {
        ctx.value?.drawImage(img, 0, 0)
      }
      img.src = props.modelValue
    }
  }
})

const startDrawing = (e: MouseEvent | TouchEvent) => {
  isDrawing.value = true
  const pos = getPosition(e)
  if (ctx.value && pos) {
    ctx.value.beginPath()
    ctx.value.moveTo(pos.x, pos.y)
  }
}

const draw = (e: MouseEvent | TouchEvent) => {
  if (!isDrawing.value || !ctx.value) return
  const pos = getPosition(e)
  if (pos) {
    ctx.value.lineTo(pos.x, pos.y)
    ctx.value.stroke()
  }
}

const stopDrawing = () => {
  isDrawing.value = false
}

const getPosition = (e: MouseEvent | TouchEvent) => {
  if (!canvasRef.value) return null
  const rect = canvasRef.value.getBoundingClientRect()

  if (e instanceof MouseEvent) {
    return {
      x: e.clientX - rect.left,
      y: e.clientY - rect.top
    }
  } else {
    const touch = e.touches[0]
    return {
      x: touch.clientX - rect.left,
      y: touch.clientY - rect.top
    }
  }
}

const clear = () => {
  if (ctx.value && canvasRef.value) {
    ctx.value.clearRect(0, 0, canvasRef.value.width, canvasRef.value.height)
    emit('update:modelValue', '')
  }
}

const save = () => {
  if (canvasRef.value) {
    const dataUrl = canvasRef.value.toDataURL('image/png')
    emit('update:modelValue', dataUrl)
  }
}
</script>

// src/components/SignaturePad.tsx
import { useEffect, useRef, useState } from "react";
import { Button } from "@heroui/react";
import { Save, X } from "lucide-react";

interface SignaturePadProps {
  label?: string;
  width?: number;
  height?: number;
  value?: string | null;
  onSave: (dataUrl: string) => void;
}

export default function SignaturePad({ label = "Signature", width = 400, height = 160, value, onSave }: SignaturePadProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const drawing = useRef(false);
  const [hasStrokes, setHasStrokes] = useState(false);

  useEffect(() => {
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");

    if (!ctx) return;
    ctx.strokeStyle = "#000";
    ctx.lineWidth = 2;
    ctx.lineCap = "round";

    if (value) {
      const img = new Image();

      img.onload = () => ctx.drawImage(img, 0, 0);
      img.src = value;
    }
  }, [value]);

  const getPos = (e: React.PointerEvent<HTMLCanvasElement>) => {
    const rect = canvasRef.current!.getBoundingClientRect();

    return { x: e.clientX - rect.left, y: e.clientY - rect.top };
  };

  const startDrawing = (e: React.PointerEvent<HTMLCanvasElement>) => {
    drawing.current = true;
    const ctx = canvasRef.current?.getContext("2d");
    const { x, y } = getPos(e);

    ctx?.beginPath();
    ctx?.moveTo(x, y);
  };

  const draw = (e: React.PointerEvent<HTMLCanvasElement>) => {
    if (!drawing.current) return;
    const ctx = canvasRef.current?.getContext("2d");
    const { x, y } = getPos(e);

    ctx?.lineTo(x, y);
    ctx?.stroke();
    setHasStrokes(true);
  };

  const stopDrawing = () => {
    drawing.current = false;
  };

  const clear = () => {
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");

    if (canvas && ctx) ctx.clearRect(0, 0, canvas.width, canvas.height);
    setHasStrokes(false);
  };

  const save = () => {
    const canvas = canvasRef.current;

    if (canvas) onSave(canvas.toDataURL("image/png"));
  };

  return (
    <div className="flex flex-col gap-2">
      <span className="text-micro font-bold uppercase tracking-wide text-muted">{label}</span>
      <div className="overflow-hidden rounded-xl border border-border bg-surface">
        <canvas
          ref={canvasRef}
          className="touch-none"
          height={height}
          style={{ cursor: "crosshair", width: "100%", maxWidth: width }}
          width={width}
          onPointerDown={startDrawing}
          onPointerLeave={stopDrawing}
          onPointerMove={draw}
          onPointerUp={stopDrawing}
        />
      </div>
      <div className="flex gap-2">
        <Button size="sm" variant="outline" onPress={clear}>
          <X className="size-4" />
          <span>Clear</span>
        </Button>
        <Button isDisabled={!hasStrokes} size="sm" variant="primary" onPress={save}>
          <Save className="size-4" />
          <span>Save Signature</span>
        </Button>
      </div>
    </div>
  );
}
